### ISSUE TITLE
Wrong pio_add_program

### ISSUE THREAD

**Issue by damian99999** [pmarques-dev/PicoEncoder#3]
I’ve got an issue in the initialization routine. It seems that by mistake, you referenced another variable, which appears to be inappropriate. Here's the fix: The PIO program loading routine should be called like this:
`pio_add_program(pio, &pico_encoder_program);`

**Comment by pmarques-dev** [comment]
arghh... you're right. I had to quickly fix a previous bug and didn't have the hardware to test the fix, so I ended up committing it without testing, which is always a risk. I'll push the fix tonight.
Thank you for finding this out and reporting it

**Comment by pmarques-dev** [comment]
btw, can you confirm that with that change in place everything works? That would allow me to just push that change without having to prepare the rig to test it with an actual encoder....

**Comment by damian99999** [comment]
With singe encoder it works so far. I will test it with 2 encoders later, maybe next week.

**Comment by pmarques-dev** [comment]
I've already pushed the version with the fix, so I think we can close this issue now. Thank you again for finding this out
